### ISSUE TITLE
Dashboard for non SuperUsers unavailable

### ISSUE THREAD

**Issue by creativejay** [gadgetto/SnipWire#2]
when a user role with snipwire-dashboard permissions clicks on the additional tabs (Orders, Subscriptions, Abandoned Carts, Customers, Products, Discounts) within the Dashboard, they reach the 404 page instead.

**Comment by gadgetto** [comment]
Fixed with latest commit in dev brach! Thanks for reporting!

**Comment by gadgetto** [comment]
Fix is included in current release 0.8.5!
Could you please check and close this issue if it works now?

**Comment by gadgetto** [comment]
Closing this now. Please reopen if necessary.
