### ISSUE TITLE
Polish Złoty missing as currency

### ISSUE THREAD

**Issue by nedkamburov** [gadgetto/SnipWire#4]
The currency is supported in the Snipcart backend but SnipWire has trouble displaying it. 

Here are 2 screenshots from Snipcart and Snipwire respectively:
![Screenshot 2020-09-16 at 17 06 50](https://user-images.githubusercontent.com/11830669/93356200-2d9b4500-f83f-11ea-88ed-9e62bab24e3c.png)
![Screenshot 2020-09-16 at 17 06 05](https://user-images.githubusercontent.com/11830669/93356205-2ecc7200-f83f-11ea-8ef2-3fd21268847d.png)

and from the front-end: 
![Screenshot 2020-09-16 at 17 09 06](https://user-images.githubusercontent.com/11830669/93356333-591e2f80-f83f-11ea-97a1-ac29253817ed.png)

**Comment by nedkamburov** [comment]
Okay, what happened with me is that SnipWire cleverly created a special field` snipcart_item_price_{currency}` but I didn't add it to my product, so there was just no info about it... I guess problem is solved, I just didn't read the manual well enough.

**Comment by gadgetto** [comment]
Great you could solve it!
I'll add check in MarkupSnipWire to catch those errors in future and to provide a useful message if a field is missing.

Thanks for reporting!
